package com.example.recetify.util

fun obtenerEmoji(nombre: String): String {
    val mapa = mapOf(
        "queso" to "🧀", "queso rallado" to "🧀", "queso parmesano" to "🧀", "parmesano" to "🧀",
        "queso azul" to "🧀", "gorgonzola" to "🧀", "roquefort" to "🧀", "queso roquefort" to "🧀",
        "mozzarella" to "🧀", "muzzarella" to "🧀", "queso mozzarella" to "🧀",
        "cheddar" to "🧀", "queso cheddar" to "🧀", "queso untable" to "🧀", "queso crema" to "🧀",
        "queso fresco" to "🧀", "provolone" to "🧀", "pategrás" to "🧀", "cremoso" to "🧀",
        "gruyere" to "🧀", "brie" to "🧀", "camembert" to "🧀","queso" to "🧀", "leche" to "🥛", "leche entera" to "🥛", "leche descremada" to "🥛", "leche en polvo" to "🥛",
        "leche de soja" to "🥛", "leche de almendras" to "🥛", "leche vegetal" to "🥛",
        "crema" to "🥛", "crema de leche" to "🥛", "nata" to "🥛",
        "yogur" to "🥛", "yogurt" to "🥛", "yogur bebible" to "🥛",
        "manteca" to "🧈", "mantequilla" to "🧈", "leche" to "🥛", "huevo" to "🥚", "huevos" to "🥚", "huevo duro" to "🥚", "huevo revuelto" to "🥚",
        "clara" to "🥚", "yema" to "🥚", "clara de huevo" to "🥚", "yema de huevo" to "🥚", "huevo" to "🥚", "tomate" to "🍅",
        "papa" to "🥔", "papas" to "🥔", "patata" to "🥔", "papas fritas" to "🥔",
        "puré de papa" to "🥔", "batata" to "🍠", "boniato" to "🍠", "papa" to "🥔", "zanahoria" to "🥕", "palta" to "🥑", "harina" to "🌾",
        "agua" to "💧", "panceta" to "🥓", "pollo" to "🍗", "carne" to "🥩",
        "pescado" to "🐟", "sal" to "🧂", "azúcar" to "🍬", "cebolla" to "🧅",
        "ajo" to "🧄", "manzana" to "🍎", "banana" to "🍌", "fresa" to "🍓",
        "pan" to "🍞", "aceite" to "🫒", "arroz" to "🍚", "fideos" to "🍝",
        "spaghetti" to "🍝", "macarrones" to "🍝", "ravioles" to "🥟", "gnocchi" to "🥟",
        "chocolate" to "🍫", "manteca" to "🧈", "crema" to "🥛", "maíz" to "🌽",
        "limón" to "🍋", "lentejas" to "🌰", "champiñón" to "🍄", "seta" to "🍄",
        "hongos" to "🍄", "berenjena" to "🍆", "pepino" to "🥒", "espinaca" to "🥬",
        "rúcula" to "🥬", "lechuga" to "🥬", "espinaca" to "🥬", "rúcula" to "🥬", "acelga" to "🥬", "kale" to "🥬", "lechuga" to "🥬", "miel" to "🍯", "nuez" to "🥜",
        "almendra" to "🥜", "avena" to "🌾", "yogur" to "🥛", "jamón" to "🥩",
        "queso rallado" to "🧀", "queso parmesano" to "🧀", "gorgonzola" to "🧀",
        "queso azul" to "🧀", "mayonesa" to "🧂", "mostaza" to "🧂", "ají" to "🌶", "chile" to "🌶", "jalapeño" to "🌶", "pimiento picante" to "🌶",
        "pimentón picante" to "🌶", "tabasco" to "🌶", "wasabi" to "🌶", "curry picante" to "🌶", "tomate" to "🍅", "tomates" to "🍅", "tomate cherry" to "🍅", "tomates cherry" to "🍅",
        "puré de tomate" to "🍅", "salsa de tomate" to "🍅", "ketchup" to "🍅", "ketchup" to "🍅",
        "salsa de soja" to "🥣", "vinagre" to "🧂", "perejil" to "🌿",  "harina" to "🌾", "harina integral" to "🌾", "avena" to "🌾", "sésamo" to "🌾",
        "chia" to "🌾", "linaza" to "🌾", "trigo" to "🌾", "cebada" to "🌾", "centeno" to "🌾", "albahaca" to "🌿",
        "orégano" to "🌿", "curry" to "🌶", "pimiento" to "🌶", "pimentón" to "🌶", "carne" to "🥩", "carne picada" to "🥩", "carne molida" to "🥩", "carne de res" to "🥩",
        "vacuno" to "🥩", "bife" to "🥩", "asado" to "🥩", "jamón" to "🥩", "lomo" to "🥩",
        "ají" to "🌶", "chile" to "🌶", "jalapeño" to "🌶", "tabasco" to "🌶", "pescado" to "🐟", "atún" to "🐟", "salmón" to "🐟", "merluza" to "🐟",
        "bacalao" to "🐟", "trucha" to "🐟", "pez espada" to "🐟",  "pan" to "🍞", "pan integral" to "🍞", "pan lactal" to "🍞", "pan de campo" to "🍞",
        "tostada" to "🍞", "tostadas" to "🍞", "galleta" to "🍪", "galletita" to "🍪", "bizcochuelo" to "🍰", "torta" to "🍰", "pastel" to "🍰",
        "postre" to "🍮", "flan" to "🍮", "helado" to "🍨", "dulce de leche" to "🍯", "mermelada" to "🍯",
        "canela" to "🌰", "vainilla" to "🌼", "anís" to "🌸", "clavo de olor" to "🌿", "manzana" to "🍎", "manzana verde" to "🍏", "banana" to "🍌", "plátano" to "🍌",
        "fresa" to "🍓", "frutilla" to "🍓", "kiwi" to "🥝", "uva" to "🍇", "agua" to "💧", "jugo" to "🧃", "licuado" to "🧃", "café" to "☕", "té" to "🍵",
        "mate" to "🧉", "vino" to "🍷", "cerveza" to "🍺", "infusión" to "🍵", "pizza" to "🍕", "hamburguesa" to "🍔", "hot dog" to "🌭", "taco" to "🌮",
        "burrito" to "🌯", "sushi" to "🍣", "falafel" to "🥙", "tortilla" to "🌮",
        "hummus" to "🥣", "tempura" to "🍤", "nori" to "🌿",
        "pera" to "🍐", "cereza" to "🍒", "sandía" to "🍉", "melón" to "🍈",
        "piña" to "🍍", "ananá" to "🍍", "mango" to "🥭", "durazno" to "🍑",
        "papaya" to "🍈", "granada" to "🍎", "arándano" to "🫐", "mora" to "🫐",
        "laurel" to "🍃", "tomillo" to "🌿", "romero" to "🌿", "caldo" to "🥣",
        "galleta" to "🍪", "bizcochuelo" to "🍰", "torta" to "🍰", "pizza" to "🍕",
        "hamburguesa" to "🍔", "hot dog" to "🌭", "cerveza" to "🍺", "vino" to "🍷",
        "té" to "🍵", "café" to "☕", "mate" to "🧉", "helado" to "🍨", "postre" to "🍮",
        "dulce de leche" to "🍯", "frutilla" to "🍓", "kiwi" to "🥝", "uva" to "🍇",
        "pera" to "🍐", "cereza" to "🍒", "sandía" to "🍉", "melón" to "🍈",
        "piña" to "🍍", "ananá" to "🍍", "mango" to "🥭", "durazno" to "🍑",
        "papaya" to "🍈", "tamarindo" to "🌰", "batata" to "🍠", "mandarina" to "🍊",
        "naranja" to "🍊", "granada" to "🍎", "arándano" to "🫐", "mora" to "🫐",
        "avellana" to "🥜", "castaña" to "🌰", "soja" to "🌿", "tofu" to "🍢",
        "edamame" to "🌿", "algas" to "🌿", "wasabi" to "🌶", "misô" to "🥣",
        "sésamo" to "🌾", "chia" to "🌾", "trigo" to "🌾", "centeno" to "🌾", "sal marina" to "🧂", "sal rosada" to "🧂", "sal negra" to "🧂",
        "azúcar moreno" to "🍬", "azúcar rubia" to "🍬", "azúcar impalpable" to "🍬", "azúcar glas" to "🍬",
        "stevia" to "🍬", "edulcorante" to "🍬", "sal marina" to "🧂", "sal rosada" to "🧂", "sal negra" to "🧂",
        "azúcar moreno" to "🍬", "azúcar rubia" to "🍬", "azúcar impalpable" to "🍬", "azúcar glas" to "🍬",
        "stevia" to "🍬", "edulcorante" to "🍬","aceite de oliva" to "🫒", "aceite vegetal" to "🫒", "aceite de girasol" to "🫒", "aceite de coco" to "🫒",
        "grasa vacuna" to "🧈", "margarina" to "🧈","aceite de oliva" to "🫒", "aceite vegetal" to "🫒", "aceite de girasol" to "🫒", "aceite de coco" to "🫒",
        "grasa vacuna" to "🧈", "margarina" to "🧈","tomate en lata" to "🥫", "arvejas en lata" to "🥫", "choclo en lata" to "🥫",
        "atún en lata" to "🥫", "sardinas" to "🥫", "pickles" to "🥫", "aceitunas" to "🫒", "aceitunas verdes" to "🫒", "aceitunas negras" to "🫒","gaseosa" to "🧃", "soda" to "🧃", "agua con gas" to "🧃",
        "bebida isotónica" to "🧃", "kombucha" to "🧃",
        "chorizo" to "🥩", "salchicha" to "🌭", "morcilla" to "🥩", "fiambre" to "🥩",
        "bondiola" to "🥩", "panceta ahumada" to "🥓", "tocino" to "🥓",
        "seitán" to "🥗", "tempeh" to "🥗", "hamburguesa vegetal" to "🥗",
        "leche de avena" to "🥛", "queso vegano" to "🧀", "pimienta" to "🌶", "pimienta negra" to "🌶", "pimienta blanca" to "🌶", "pimienta rosa" to "🌶",
        "pimienta verde" to "🌶", "pimienta roja" to "🌶", "pimienta molida" to "🌶", "pimienta en grano" to "🌶",
        "pimienta recién molida" to "🌶", "mezcla de pimientas" to "🌶", "cuatro pimientas" to "🌶",
        "pimienta cayena" to "🌶", "cayena" to "🌶", "pimienta de cayena" to "🌶",
        "pimienta de jamaica" to "🌶", "allspice" to "🌶",
        "pimienta negra molida" to "🌶", "pimienta negra en grano" to "🌶",

        "portobello" to "🍄", "champiñones" to "🍄", "shitake" to "🍄", "boletus" to "🍄",
        "empanada" to "🥟", "empanadas" to "🥟", "tartaleta" to "🍰", "croissant" to "🥐", "medialuna" to "🥐",
        "baguette" to "🥖", "brioche" to "🥐", "pan árabe" to "🥙", "pita" to "🥙",
        "esencia de vainilla" to "🌼", "esencia de almendra" to "🌰",
        "extracto de café" to "☕", "agua de azahar" to "🌼", "ralladura de limón" to "🍋", "ralladura de naranja" to "🍊",
        "levadura" to "🧪", "levadura seca" to "🧪", "polvo de hornear" to "🧪",
        "bicarbonato de sodio" to "🧪", "gelatina" to "🧪", "agar agar" to "🧪",
        "congelado" to "🧊", "rallado" to "🔪", "triturado" to "🔪",
        "picado" to "🔪", "fileteado" to "🔪", "cocido" to "🔥", "crudo" to "🥗",
        "hervido" to "🍲", "al vapor" to "♨️", "a la plancha" to "🍳",
        "cebada" to "🌾", "hummus" to "🥣", "falafel" to "🥙", "tortilla" to "🌮",
        "taco" to "🌮", "burrito" to "🌯", "sushi" to "🍣", "nori" to "🌿",
        "tempura" to "🍤", "wasabi" to "🌶", "salmón" to "🐟", "atun" to "🐟","echalote" to "🧄", "cebollín" to "🧄", "cebolla de verdeo" to "🧄", "cebolleta" to "🧄",
        "puerro" to "🧄", "jengibre" to "🧄", "ajo en polvo" to "🧄", "cebolla en polvo" to "🧅"

    )
    return mapa.entries.firstOrNull { nombre.lowercase().contains(it.key) }?.value ?: "🍽"
}
