package com.example.recetify.util

/**
 * Utilitario para gestionar emojis representativos según fragmentos de texto en el nombre.
 */
private val emojiMap = mapOf(
    "queso" to "🧀",
    "queso rallado" to "🧀",
    "queso parmesano" to "🧀",
    "parmesano" to "🧀",
    "queso azul" to "🧀",
    "gorgonzola" to "🧀",
    "roquefort" to "🧀",
    "queso roquefort" to "🧀",
    "mozzarella" to "🧀",
    "muzzarella" to "🧀",
    "queso mozzarella" to "🧀",
    "cheddar" to "🧀",
    "queso cheddar" to "🧀",
    "queso untable" to "🧀",
    "queso crema" to "🧀",
    "queso fresco" to "🧀",
    "provolone" to "🧀",
    "pategrás" to "🧀",
    "cremoso" to "🧀",
    "gruyere" to "🧀",
    "brie" to "🧀",
    "camembert" to "🧀",
    "leche" to "🥛",
    "leche entera" to "🥛",
    "leche descremada" to "🥛",
    "leche en polvo" to "🥛",
    "leche de soja" to "🥛",
    "leche de almendras" to "🥛",
    "leche vegetal" to "🥛",
    "crema" to "🥛",
    "crema de leche" to "🥛",
    "nata" to "🥛",
    "yogur" to "🥛",
    "yogurt" to "🥛",
    "yogur bebible" to "🥛",
    "manteca" to "🧈",
    "mantequilla" to "🧈",
    "huevo" to "🥚",
    "huevos" to "🥚",
    "huevo duro" to "🥚",
    "huevo revuelto" to "🥚",
    "clara" to "🥚",
    "yema" to "🥚",
    "clara de huevo" to "🥚",
    "yema de huevo" to "🥚",
    "tomate" to "🍅",
    "tomates" to "🍅",
    "tomate cherry" to "🍅",
    "tomates cherry" to "🍅",
    "puré de tomate" to "🍅",
    "salsa de tomate" to "🍅",
    "ketchup" to "🍅",
    "papa" to "🥔",
    "papas" to "🥔",
    "patata" to "🥔",
    "papas fritas" to "🥔",
    "puré de papa" to "🥔",
    "batata" to "🍠",
    "boniato" to "🍠",
    "zanahoria" to "🥕",
    "palta" to "🥑",
    "harina" to "🌾",
    "harina integral" to "🌾",
    "avena" to "🌾",
    "trigo" to "🌾",
    "cebada" to "🌾",
    "centeno" to "🌾",
    "sésamo" to "🌾",
    "chia" to "🌾",
    "linaza" to "🌾",
    "aceite" to "🫒",
    "aceite de oliva" to "🫒",
    "aceite vegetal" to "🫒",
    "aceite de girasol" to "🫒",
    "aceite de coco" to "🫒",
    "grasa vacuna" to "🧈",
    "margarina" to "🧈",
    "agua" to "💧",
    "café" to "☕",
    "té" to "🍵",
    "mate" to "🧉",
    "jugo" to "🧃",
    "licuado" to "🧃",
    "cerveza" to "🍺",
    "vino" to "🍷",
    "gaseosa" to "🧃",
    "soda" to "🧃",
    "agua con gas" to "🧃",
    "bebida isotónica" to "🧃",
    "kombucha" to "🧃",
    "pollo" to "🍗",
    "pescado" to "🐟",
    "atún" to "🐟",
    "salmón" to "🐟",
    "merluza" to "🐟",
    "bacalao" to "🐟",
    "trucha" to "🐟",
    "pez espada" to "🐟",
    "carne" to "🥩",
    "carne picada" to "🥩",
    "carne molida" to "🥩",
    "carne de res" to "🥩",
    "vacuno" to "🥩",
    "bife" to "🥩",
    "asado" to "🥩",
    "jamón" to "🥩",
    "lomo" to "🥩",
    "panceta" to "🥓",
    "tocino" to "🥓",
    "salchicha" to "🌭",
    "chorizo" to "🥩",
    "morcilla" to "🥩",
    "bondiola" to "🥩",
    "pan" to "🍞",
    "pan integral" to "🍞",
    "pan lactal" to "🍞",
    "pan de campo" to "🍞",
    "tostada" to "🍞",
    "tostadas" to "🍞",
    "galleta" to "🍪",
    "galletita" to "🍪",
    "bizcochuelo" to "🍰",
    "torta" to "🍰",
    "pastel" to "🍰",
    "postre" to "🍮",
    "flan" to "🍮",
    "helado" to "🍨",
    "dulce de leche" to "🍯",
    "mermelada" to "🍯",
    "azúcar" to "🍬",
    "azúcar moreno" to "🍬",
    "azúcar rubia" to "🍬",
    "azúcar impalpable" to "🍬",
    "azúcar glas" to "🍬",
    "stevia" to "🍬",
    "edulcorante" to "🍬",
    "sal marina" to "🧂",
    "sal rosada" to "🧂",
    "sal negra" to "🧂",
    "vinagre" to "🧂",
    "mostaza" to "🧂",
    "mayonesa" to "🧂",
    "perejil" to "🌿",
    "albahaca" to "🌿",
    "orégano" to "🌿",
    "romero" to "🌿",
    "tomillo" to "🌿",
    "laurel" to "🍃",
    "cilantro" to "🌿",
    "perejil" to "🌿",
    "pimentón" to "🌶",
    "ají" to "🌶",
    "chile" to "🌶",
    "jalapeño" to "🌶",
    "tabasco" to "🌶",
    "wasabi" to "🌶",
    "curry" to "🌶",
    "pimienta" to "🌶",
    "fileteado" to "🔪",
    "picado" to "🔪",
    "rallado" to "🔪",
    "triturado" to "🔪",
    "cocido" to "🔥",
    "hervido" to "🍲",
    "a la plancha" to "🍳",
    "al vapor" to "♨️",
    "congelado" to "🧊",
    "tofu" to "🍢",
    "seitán" to "🥗",
    "tempeh" to "🥗",
    "hamburguesa vegetal" to "🥗",
    "hummus" to "🥣",
    "falafel" to "🥙",
    "tortilla" to "🌮",
    "taco" to "🌮",
    "burrito" to "🌯",
    "sushi" to "🍣",
    "tempura" to "🍤",
    "nori" to "🌿",
    "pizza" to "🍕",
    "hamburguesa" to "🍔",
    "hot dog" to "🌭"
)

/**
 * Devuelve un emoji según fragmentos del nombre.
 */
fun obtenerEmoji(nombre: String): String {
    val lower = nombre.lowercase()
    return emojiMap.entries
        .firstOrNull { (key, _) -> lower.contains(key) }
        ?.value
        ?: "🍽"
}

/**
 * Lista ordenada de todas las claves (ingredientes) disponibles.
 */
fun listaIngredientesConEmoji(): List<String> =
    emojiMap.keys
        .map { it.replaceFirstChar { c -> c.uppercase() } }
        .sorted()