package com.example.recetify.util

/**
 * Utilitario para gestionar emojis representativos según fragmentos de texto en el nombre.
 */
private val emojiMap = mapOf(
    "queso" to "🧀",
    "queso rallado" to "🧀",
    "queso parmesano" to "🧀",
    "parmesano" to "🧀",
    "queso azul" to "🧀",
    "gorgonzola" to "🧀",
    "roquefort" to "🧀",
    "queso roquefort" to "🧀",
    "mozzarella" to "🧀",
    "muzzarella" to "🧀",
    "queso mozzarella" to "🧀",
    "cheddar" to "🧀",
    "queso cheddar" to "🧀",
    "queso untable" to "🧀",
    "queso crema" to "🧀",
    "queso fresco" to "🧀",
    "provolone" to "🧀",
    "pategrás" to "🧀",
    "cremoso" to "🧀",
    "gruyere" to "🧀",
    "brie" to "🧀",
    "camembert" to "🧀",
    "leche" to "🥛",
    "leche entera" to "🥛",
    "leche descremada" to "🥛",
    "leche en polvo" to "🥛",
    "leche de soja" to "🥛",
    "leche de almendras" to "🥛",
    "leche vegetal" to "🥛",
    "crema" to "🥛",
    "crema de leche" to "🥛",
    "nata" to "🥛",
    "yogur" to "🥛",
    "yogurt" to "🥛",
    "yogur bebible" to "🥛",
    "manteca" to "🧈",
    "mantequilla" to "🧈",
    "huevo" to "🥚",
    "huevos" to "🥚",
    "huevo duro" to "🥚",
    "huevo revuelto" to "🥚",
    "clara" to "🥚",
    "yema" to "🥚",
    "clara de huevo" to "🥚",
    "yema de huevo" to "🥚",
    "tomate" to "🍅",
    "tomate cherry" to "🍅",
    "tomates cherry" to "🍅",
    "puré de tomate" to "🍅",
    "salsa de tomate" to "🍅",
    "ketchup" to "🍅",
    "papa" to "🥔",
    "papas" to "🥔",
    "patata" to "🥔",
    "papas fritas" to "🥔",
    "puré de papa" to "🥔",
    "batata" to "🍠",
    "boniato" to "🍠",
    "zanahoria" to "🥕",
    "palta" to "🥑",
    "harina" to "🌾",
    "harina integral" to "🌾",
    "avena" to "🌾",
    "trigo" to "🌾",
    "cebada" to "🌾",
    "centeno" to "🌾",
    "sésamo" to "🌾",
    "chia" to "🌾",
    "linaza" to "🌾",
    "aceite" to "🫒",
    "aceite de oliva" to "🫒",
    "aceite vegetal" to "🫒",
    "aceite de girasol" to "🫒",
    "aceite de coco" to "🫒",
    "grasa vacuna" to "🧈",
    "margarina" to "🧈",
    "agua" to "💧",
    "café" to "☕",
    "té" to "🍵",
    "mate" to "🧉",
    "jugo" to "🧃",
    "licuado" to "🧃",
    "cerveza" to "🍺",
    "vino" to "🍷",
    "gaseosa" to "🧃",
    "soda" to "🧃",
    "agua con gas" to "🧃",
    "bebida isotónica" to "🧃",
    "kombucha" to "🧃",
    "pollo" to "🍗",
    "pescado" to "🐟",
    "atún" to "🐟",
    "salmón" to "🐟",
    "merluza" to "🐟",
    "bacalao" to "🐟",
    "trucha" to "🐟",
    "pez espada" to "🐟",
    "carne" to "🥩",
    "carne picada" to "🥩",
    "carne molida" to "🥩",
    "carne de res" to "🥩",
    "vacuno" to "🥩",
    "bife" to "🥩",
    "asado" to "🥩",
    "jamón" to "🥩",
    "lomo" to "🥩",
    "panceta" to "🥓",
    "tocino" to "🥓",
    "salchicha" to "🌭",
    "chorizo" to "🥩",
    "morcilla" to "🥩",
    "bondiola" to "🥩",
    "pan" to "🍞",
    "pan integral" to "🍞",
    "pan lactal" to "🍞",
    "pan de campo" to "🍞",
    "tostada" to "🍞",
    "tostadas" to "🍞",
    "galleta" to "🍪",
    "galletita" to "🍪",
    "bizcochuelo" to "🍰",
    "torta" to "🍰",
    "pastel" to "🍰",
    "postre" to "🍮",
    "flan" to "🍮",
    "helado" to "🍨",
    "dulce de leche" to "🍯",
    "mermelada" to "🍯",
    "azúcar" to "🍬",
    "azúcar moreno" to "🍬",
    "azúcar rubia" to "🍬",
    "azúcar impalpable" to "🍬",
    "azúcar glas" to "🍬",
    "stevia" to "🍬",
    "edulcorante" to "🍬",
    "sal marina" to "🧂",
    "sal rosada" to "🧂",
    "sal negra" to "🧂",
    "vinagre" to "🧂",
    "mostaza" to "🧂",
    "mayonesa" to "🧂",
    "perejil" to "🌿",
    "albahaca" to "🌿",
    "orégano" to "🌿",
    "romero" to "🌿",
    "tomillo" to "🌿",
    "laurel" to "🍃",
    "cilantro" to "🌿",
    "perejil" to "🌿",
    "pimentón" to "🌶",
    "ají" to "🌶",
    "chile" to "🌶",
    "jalapeño" to "🌶",
    "tabasco" to "🌶",
    "wasabi" to "🌶",
    "curry" to "🌶",
    "pimienta" to "🌶",
    "fileteado" to "🔪",
    "picado" to "🔪",
    "rallado" to "🔪",
    "triturado" to "🔪",
    "cocido" to "🔥",
    "hervido" to "🍲",
    "a la plancha" to "🍳",
    "al vapor" to "♨️",
    "congelado" to "🧊",
    "tofu" to "🍢",
    "seitán" to "🥗",
    "tempeh" to "🥗",
    "hamburguesa vegetal" to "🥗",
    "hummus" to "🥣",
    "falafel" to "🥙",
    "tortilla" to "🌮",
    "taco" to "🌮",
    "burrito" to "🌯",
    "sushi" to "🍣",
    "tempura" to "🍤",
    "nori" to "🌿",
    "pizza" to "🍕",
    "hamburguesa" to "🍔",
    "hot dog" to "🌭",
    "acelga" to "🥬",
    "ajo" to "🧄",
    "ají molido" to "🌶",
    "almendras" to "🌰",
    "arroz" to "🍚",
    "banana" to "🍌",
    "bicarbonato de sodio" to "🧂",
    "calabaza" to "🎃",
    "canela" to "🟤",
    "cebolla" to "🧅",
    "choclo" to "🌽",
    "chocolate" to "🍫",
    "clavo de olor" to "🟤",
    "coco rallado" to "🥥",
    "comino" to "🌿",
    "espinaca" to "🥬",
    "fideos" to "🍝",
    "filete de pescado" to "🐟",
    "frutilla" to "🍓",
    "garbanzos" to "🟤",
    "huevo batido" to "🥚",
    "jamón cocido" to "🥩",
    "jamón crudo" to "🥩",
    "lentejas" to "🟤",
    "levadura" to "🍞",
    "manzana" to "🍎",
    "masa de empanada" to "🥟",
    "masa de pizza" to "🍕",
    "masa de tarta" to "🥧",
    "miel" to "🍯",
    "nueces" to "🌰",
    "nuez moscada" to "🟤",
    "pan rallado" to "🍞",
    "paprika" to "🌶",
    "pasas de uva" to "🍇",
    "pollo desmenuzado" to "🍗",
    "polvo de hornear" to "🎂",
    "porotos" to "🟤",
    "puerro" to "🧅",
    "sal" to "🧂",
    "salsa de soja" to "🧂",
    "salsa inglesa" to "🧂",
    "tomate triturado" to "🍅",
    "tortilla de trigo" to "🌮",
    "vainilla" to "🌸",
    "alcaparras" to "🫒",
    "aceitunas" to "🫒",
    "espárragos" to "🥬",
    "brocoli" to "🥦",
    "coliflor" to "🥦",
    "zapallito" to "🥒",
    "zucchini" to "🥒",
    "rúcula" to "🥬",
    "hinojo" to "🥬",
    "nabo" to "🥕",
    "rábano" to "🥕",
    "pepino" to "🥒",
    "morron" to "🌶",
    "pimiento" to "🌶",
    "berenjena" to "🍆",
    "apio" to "🥬",
    "soja" to "🟤",
    "edamame" to "🟢",
    "tofu firme" to "🍢",
    "tempeh marinado" to "🍢",
    "seitán casero" to "🥩",
    "mijo" to "🌾",
    "quinoa" to "🌾",
    "trigo burgol" to "🌾",
    "cuscús" to "🌾",
    "arroz yamani" to "🍚",
    "arroz integral" to "🍚",
    "macarrones" to "🍝",
    "tallarines" to "🍝",
    "spaghetti" to "🍝",
    "ravioles" to "🍝",
    "ñoquis" to "🍝",
    "lasaña" to "🍝",
    "crepes" to "🥞",
    "panqueques" to "🥞",
    "croissant" to "🥐",
    "medialuna" to "🥐",
    "factura" to "🥐",
    "donas" to "🍩",
    "budín" to "🍰",
    "alfajor" to "🍪",
    "brownie" to "🍫",
    "turrón" to "🍬",
    "mazapán" to "🍬",
    "fruta abrillantada" to "🍍",
    "fruta confitada" to "🍍",
    "dátiles" to "🍇",
    "ciruelas secas" to "🍇",
    "higos secos" to "🍇",
    "avellanas" to "🌰",
    "castañas" to "🌰",
    "menta" to "🌿",
    "salvia" to "🌿",
    "estragón" to "🌿",
    "eneldo" to "🌿",
    "galanga" to "🌿",
    "lemongrass" to "🌿",
    "hojas de curry" to "🌿",
    "hojas de lima kaffir" to "🌿",
    "jengibre" to "🫚",
    "curcuma fresca" to "🟤",
    "trigo sarraceno" to "🌾",
    "cebolla morada" to "🧅",
    "cebolla de verdeo" to "🧅",
    "ajo negro" to "🧄",
    "pasta de maní" to "🥜",
    "leche condensada" to "🥛",
    "leche evaporada" to "🥛",
    "harina de garbanzos" to "🌾",
    "fécula de maíz" to "🌽",
    "sémola" to "🌾",
    "queso provolone" to "🧀",
    "queso fontina" to "🧀",
    "queso ricotta" to "🧀",
    "queso cottage" to "🧀",
    "queso mascarpone" to "🧀",
    "queso feta" to "🧀",
    "queso halloumi" to "🧀",
    "queso curado" to "🧀",
    "manteca clarificada" to "🧈",
    "huevo poché" to "🥚",
    "huevo frito" to "🥚",
    "clara montada" to "🥚",
    "yema cocida" to "🥚",
    "leche de coco" to "🥛",
    "leche de avena" to "🥛",
    "leche de castañas" to "🥛",
    "leche de arroz" to "🥛",
    "leche de nuez" to "🥛",
    "carne de cerdo" to "🥩",
    "pierna de pollo" to "🍗",
    "hígado" to "🥩",
    "riñón" to "🥩",
    "carne de cordero" to "🥩",
    "conejo" to "🐇",
    "codorniz" to "🐦",
    "gambas" to "🦐",
    "langostinos" to "🦐",
    "camarones" to "🦐",
    "calamares" to "🦑",
    "pulpo" to "🐙",
    "mejillones" to "🦪",
    "almejas" to "🦪",
    "ostras" to "🦪",
    "surimi" to "🦀",
    "caracol" to "🐌",
    "anchoas" to "🐟",
    "huevas de pescado" to "🥚",
    "bacón vegetal" to "🥓",
    "mandarina" to "🍊",
    "pomelo" to "🍊",
    "arándanos" to "🫐",
    "mora" to "🫐",
    "frambuesa" to "🍓",
    "kiwi" to "🥝",
    "papaya" to "🟠",
    "granada" to "🔴",
    "guayaba" to "🟢",
    "tamarindo" to "🟤",
    "durazno" to "🍑",
    "nectarina" to "🍑",
    "melocotón" to "🍑",
    "sandía" to "🍉",
    "melón" to "🍈",
    "uva blanca" to "🍇",
    "ciruela" to "🟣",
    "pera" to "🍐",
    "castaña de cajú" to "🌰",
    "pistacho" to "🌰",
    "piñones" to "🌰",
    "semillas de calabaza" to "🌰",
    "semillas de girasol" to "🌻",
    "semillas de amapola" to "🌾",
    "semillas de sésamo negro" to "🌾",
    "pimienta blanca" to "🌶",
    "pimienta negra" to "🌶",
    "ajo en polvo" to "🧄",
    "cebolla en polvo" to "🧅",
    "cúrcuma" to "🟡",
    "pasta de curry" to "🍛",
    "galanga" to "🟤",
    "miso" to "🥣",
    "salsa hoisin" to "🧂",
    "salsa teriyaki" to "🧂",
    "tahini" to "🥣",
    "ghee" to "🧈",
    "harina de arroz" to "🌾",
    "harina de almendras" to "🌾",
    "almidón de mandioca" to "🌽",
    "fécula de papa" to "🥔",
    "yuca" to "🥔",
    "plátano" to "🍌",
    "banana verde" to "🍌",
    "batata morada" to "🍠",
    "pepino dulce" to "🥒",
    "tomatillo" to "🍅",
    "mango" to "🥭",
    "lichi" to "🍒",
    "rambután" to "🍒",
    "champiñones" to "🍄",
    "hongos portobello" to "🍄",
    "shiitake" to "🍄",
    "enoki" to "🍄",
    "trufa" to "🍄",
    "caviar" to "🖤",
    "alga wakame" to "🌿",
    "alga kombu" to "🌿",
    "harina de coco" to "🥥",
    "harina de avena" to "🌾",
    "aceite de sésamo" to "🫒",
    "aceite de maíz" to "🫒",
    "aceite de palta" to "🫒",
    "sal de apio" to "🧂",
    "ajo en escamas" to "🧄",
    "levadura nutricional" to "🍞",
    "sal ahumada" to "🧂",
    "vinagre balsámico" to "🧂",
    "vinagre de manzana" to "🧂",
    "mostaza en grano" to "🧂",
    "pasta de maní" to "🥜",
    "pasta de almendras" to "🌰",
    "pasta de avellanas" to "🌰",
    "extracto de vainilla" to "🌸",
    "pasta de dátiles" to "🍇",
    "azúcar de coco" to "🍬",
    "azúcar mascabo" to "🍬",
    "azúcar de caña" to "🍬",
    "leche de anacardos" to "🥛",
    "leche de macadamia" to "🥛",
    "agua de coco" to "🥥",
    "bebida de arroz" to "🥛",
    "yogur griego" to "🥛",
    "queso de cabra" to "🧀",
    "queso vegano" to "🧀",
    "queso de almendras" to "🧀",
    "tofu ahumado" to "🍢",
    "tempeh frito" to "🍢",
    "hamburguesa de lentejas" to "🥙",
    "hamburguesa de garbanzos" to "🥙",
    "salsa pesto" to "🌿",
    "salsa bechamel" to "🥣",
    "salsa blanca" to "🥣",
    "salsa criolla" to "🧂",
    "chimichurri" to "🧂",
    "pesto rosso" to "🧂",
    "crema agria" to "🥛",
    "crema vegetal" to "🥛",
    "agua tónica" to "🧃",
    "vino blanco" to "🍷",
    "vino tinto" to "🍷",
    "tamarindo" to "🥭",
    "mandarina" to "🍊",
    "pomelo" to "🍊",
    "durazno" to "🍑",
    "nectarina" to "🍑",
    "pera" to "🍐",
    "mango" to "🥭",
    "granada" to "🍎",
    "kiwi" to "🥝",
    "uva blanca" to "🍇",
    "uva negra" to "🍇",
    "arándanos" to "🫐",
    "moras" to "🫐",
    "frambuesas" to "🍓",
    "guanábana" to "🥥",
    "papaya" to "🥭",
    "chirimoya" to "🥭",
    "ananá" to "🍍",
    "piña" to "🍍",
    "pepitas de calabaza" to "🌰",
    "semillas de girasol" to "🌻",
    "semillas de amapola" to "🌼",
    "semillas de cáñamo" to "🌾",
    "pistachos" to "🌰",
    "anacardos" to "🌰",
    "macadamias" to "🌰",
    "frutas secas" to "🥭",
    "frutas deshidratadas" to "🍌",
    "banana deshidratada" to "🍌",
    "cebollín" to "🧅",
    "escarola" to "🥬",
    "radicchio" to "🥬",
    "col rizada" to "🥬",
    "col lombarda" to "🥬",
    "repollo" to "🥬",
    "grelos" to "🥬",
    "escaramujo" to "🌹",
    "romanesco" to "🥦",
    "brotes de soja" to "🌱",
    "brotes de alfalfa" to "🌱",
    "germen de trigo" to "🌾",
    "polen" to "🍯",
    "miso" to "🥣",
    "sriracha" to "🌶",
    "gochujang" to "🌶",
    "kimchi" to "🥬",
    "salsa teriyaki" to "🧂",
    "salsa de ostras" to "🦪",
    "salsa hoisin" to "🧂",
    "salsa barbacoa" to "🧂",
    "arroz jazmín" to "🍚",
    "arroz basmati" to "🍚",
    "arroz salvaje" to "🌾",
    "trigo sarraceno" to "🌾", // ya estaba en otra parte pero comúnmente omitido
    "espelta" to "🌾",
    "kamut" to "🌾",
    "teff" to "🌾",
    "amapola" to "🌾",
    "ajo en escamas" to "🧄",
    "cebolla caramelizada" to "🧅",
    "tomate seco" to "🍅",
    "pesto" to "🌿",
    "anchoas" to "🐟",
    "surimi" to "🍥",
    "huevo de codorniz" to "🥚",
    "huevo de pato" to "🥚",
    "nata montada" to "🥛",
    "leche de cabra" to "🥛",
    "crema agria" to "🥛",
    "queso de cabra" to "🧀",
    "ricotta salata" to "🧀",
    "queso de oveja" to "🧀",
    "queso de almendras" to "🧀",
    "mayonesa vegana" to "🧂",
    "sirope de agave" to "🍯",
    "melaza" to "🍯",
    "jarabe de arce" to "🍯",
    "azúcar de coco" to "🍬",
    "salvia fresca" to "🌿",
    "hierba buena" to "🌿",
    "ramitas de tomillo" to "🌿",
    "levadura nutricional" to "🍞",
    "chucrut" to "🥬",
    "kimchi" to "🥬",
    "pickles" to "🥒",
    "pepinillos" to "🥒",
    "tamarindo en pasta" to "🟤",
    "harina de coco" to "🌾",
    "fibra de avena" to "🌾",
    "col rizada" to "🥬",
    "kale" to "🥬",
    "nabo daikon" to "🥬",
    "alga wakame" to "🌿",
    "alga kombu" to "🌿",
    "gelatina" to "🍮",
    "agar agar" to "🍮",
    "proteína en polvo" to "💪",
    "caseína" to "💪",
    "creatina" to "⚡",
    "col rizada" to "🥬",
    "champiñones" to "🍄",
    "ciboulette" to "🌿",
    "pesto" to "🌿",
    "nibs de cacao" to "🍫",
    "aceite de sésamo" to "🫒",
    "vinagre balsámico" to "🧂",
    "mostaza antigua" to "🧂",
    "alga kombu" to "🌿",
    "hongo maitake" to "🍄",
    "levadura nutricional" to "🧂",
    "harina de coco" to "🥥",
    "harina de almendras" to "🌰",
    "harina de avena" to "🌾",
    "agua de azahar" to "🌸",
    "ralladura de limón" to "🍋",
    "ralladura de naranja" to "🍊",
    "semillas de amapola" to "🌾",
    "semillas de girasol" to "🌻",
    "semillas de calabaza" to "🎃",
    "ajo en polvo" to "🧄",
    "cebolla en polvo" to "🧅",
    "jengibre en polvo" to "🫚",
    "canela en rama" to "🟤",
    "anís estrellado" to "⭐",
    "cardamomo" to "🌿",
    "harina leudante" to "🌾",
    "fécula de mandioca" to "🌽",
    "fécula de papa" to "🥔",
    "polenta" to "🌽",
    "coco rallado" to "🥥",
    "queso vegano" to "🧀",
    "hamburguesa de lentejas" to "🥙",
    "fideos de arroz" to "🍜",
    "pasta integral" to "🍝",
    "masa filo" to "🥟",
    "nata vegetal" to "🥛",
    "crema agria" to "🥛",
    "sour cream" to "🥛",
    "dulce de membrillo" to "🍎",
    "dulce de batata" to "🍠",
    "gelatina sin sabor" to "🍮",
    "agar-agar" to "🍮",
    "goma xántica" to "🧬",
    "proteína en polvo" to "🥤",
    "colágeno en polvo" to "🧬",
    "chia hidratada" to "🌾",
    "banana pisada" to "🍌",
    "huevo de lino" to "🥚",
    "huevo vegano" to "🥚",
    "harina de trigo sarraceno" to "🌾",
    "almidón de maíz" to "🌽",
    "harina de arroz" to "🌾",
    "vinagre de manzana" to "🧂",
    "vinagre de arroz" to "🧂",
    "cacao amargo" to "🍫",
    "chocolate amargo" to "🍫",
    "chocolate blanco" to "🍫",
    "esencia de vainilla" to "🌸",
    "colorante vegetal" to "🎨",
    "gluten de trigo" to "🌾",
    "proteína vegetal texturizada" to "🌿",
    "mayonesa vegana" to "🧂",
    "queso rallado vegano" to "🧀",
    "coco fresco" to "🥥",
    "azúcar mascabo" to "🍬",
    "harina 0000" to "🌾",
    "harina 000" to "🌾",
    "leche de cabra" to "🥛",
    "queso de cabra" to "🧀",
    "yogur griego" to "🥛",
    "crema vegetal" to "🥛",
    "leche de pistacho" to "🥛",
    "mantequilla de maní" to "🥜",
    "mantequilla de almendras" to "🥜",
    "polvo de matcha" to "🍵",
    "té chai" to "🍵",
    "agua de coco" to "🥥",
    "agua saborizada" to "💧",
    "sirope de agave" to "🍯",
    "sirope de maple" to "🍁",
    "melaza" to "🍯",
    "malta" to "🌾",
    "pan de centeno" to "🍞",
    "pan de salvado" to "🍞",
    "cereal inflado" to "🥣",
    "granola sin azúcar" to "🥣",
    "semillas de lino molidas" to "🌾",
    "fibra de cáscara de psyllium" to "🌿",
    "harina de soja" to "🌾",
    "hojuelas de avena" to "🌾",
    "almendras laminadas" to "🌰",
    "nueces pecan" to "🌰",
    "arándanos deshidratados" to "🫐",
    "frambuesas" to "🍓",
    "moras" to "🫐",
    "zanahoria rallada" to "🥕",
    "manzana rallada" to "🍎",
    "batata al horno" to "🍠",
    "caviar" to "🐟",
    "ghee" to "🧈",
    "trufa" to "🍄",
    "aceite de trufa" to "🫒",
    "mostaza de Dijon" to "🧂",
    "sal en escamas" to "🧂",
    "sal ahumada" to "🧂",
    "pimienta blanca" to "🌶",
    "pimienta rosa" to "🌸",
    "azafrán" to "🌺",
    "curcuma en polvo" to "🟤",
    "vino blanco" to "🍷",
    "vino tinto" to "🍷",
    "coñac" to "🥃",
    "whisky" to "🥃",
    "champagne" to "🍾",
    "agua de azahar" to "🌸",
    "rosa mosqueta" to "🌹",
    "flores comestibles" to "🌸",
    "tamarindo" to "🥭",
    "nopal" to "🌵",
    "alga wakame" to "🌿",
    "alga kombu" to "🌿",
    "alga espirulina" to "🌿",
    "chucrut" to "🥬",
    "kimchi" to "🌶",
    "soja texturizada" to "🌿",
    "proteína de arveja" to "🟢",
    "té negro" to "🍵",
    "té verde" to "🍵",
    "yerba mate" to "🧉",
    "agua de rosas" to "🌹",
    "miso" to "🥣",
    "dashi" to "🍲",
    "bulgur" to "🌾",
    "harina de mijo" to "🌾",
    "caramelo líquido" to "🍯",
    "crutones" to "🍞",
    "carne de cerdo" to "🥩",
    "corteza de cerdo" to "🥓",
    "salmón ahumado" to "🐟",
    "bacón vegano" to "🥓",
    "jamón vegetal" to "🥩",
    "queso de almendras" to "🧀",
    "nata vegetal" to "🥛",
    "café instantáneo" to "☕",
    "hielo triturado" to "🧊",
    "clavo de especia" to "🟤",
    "anis estrellado" to "🌟",
    "caldo de verdura" to "🥣",
    "polenta" to "🌽",
    "semillas de girasol" to "🌻",
    "semillas de calabaza" to "🎃",
    "semillas de amapola" to "🌸",
    "semillas de lino" to "🌾",
    "semillas de chía" to "🌾",
    "té de jazmín" to "🌼",
    "té de hibisco" to "🌺",
    "agua de coco" to "🥥",
    "jarabe de arce" to "🍁",
    "sirope de agave" to "🍯",
    "cáscara de limón" to "🍋",
    "cáscara de naranja" to "🍊",
    "zeste de lima" to "🍈",
    "hojas de menta" to "🌿",
    "hojas de parra" to "🍃",
    "aceite de sésamo" to "🫒",
    "aceite de maní" to "🫒",
    "aceite de palta" to "🫒",
    "col rizada" to "🥬",
    "col lombarda" to "🥬",
    "repollo" to "🥬",
    "hojas de mostaza" to "🥬",
    "brotes de soja" to "🟢",
    "brotes de alfalfa" to "🌱",
    "germen de trigo" to "🌾",
    "hongo shiitake" to "🍄",
    "hongo portobello" to "🍄",
    "hongo enoki" to "🍄",
    "setas variadas" to "🍄",
    "coliflor morada" to "🥦",
    "zanahoria morada" to "🥕",
    "papines andinos" to "🥔",
    "ají amarillo" to "🌶",
    "ají panca" to "🌶",
    "rocoto" to "🌶",
    "naranja agria" to "🍊",
    "pepino dulce" to "🥒",
    "arándanos" to "🫐",
    "zarzamora" to "🫐",
    "frambuesa" to "🍓",
    "guayaba" to "🍈",
    "mango verde" to "🥭",
    "pitahaya" to "🐉",
    "mangostán" to "🥭",
    "lichi" to "🍒",
    "longan" to "🍒",
    "papaya verde" to "🥭",
    "melón amargo" to "🍈"
    )

/**
 * Devuelve un emoji según fragmentos del nombre.
 */
fun obtenerEmoji(nombre: String): String {
    val lower = nombre.lowercase()
    return emojiMap.entries
        .firstOrNull { (key, _) -> lower.contains(key) }
        ?.value
        ?: "🍽"
}

/**
 * Lista ordenada de todas las claves (ingredientes) disponibles.
 */
fun listaIngredientesConEmoji(): List<String> =
    emojiMap.keys
        .map { it.replaceFirstChar { c -> c.uppercase() } }
        .sorted()